version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: amazon-nginx
    restart: on-failure
    volumes:
      - './public/:/usr/src/app:cached'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - "8000:80"
    depends_on:
      - php
  php:
    container_name: amazon-php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    restart: on-failure
    volumes:
      - .:/usr/src/app:cached
      - ~/.ssh:/root/.ssh:ro
      - ~/.composer:/root/.composer
